"""
Django settings for medinet project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import json
from cryptography.fernet import Fernet

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Configuration directory for secrets (auto-generated by Docker entrypoint)
CONFIG_DIR = BASE_DIR / 'config'


# ==============================================================================
# SECURITY: SECRET_KEY Configuration
# ==============================================================================
# SECURITY WARNING: keep the secret key used in production secret!
#
# The SECRET_KEY is loaded from a file for better security:
# 1. In Docker: Auto-generated on first run by entrypoint.sh
# 2. In local dev: Falls back to environment variable or default
#
# Production: Ensure the secret key file exists in the config directory

def load_secret_key():
    """
    Load SECRET_KEY from file, environment variable, or fallback to default.
    Priority: File > Environment Variable > Default (dev only)
    """
    secret_key_file = CONFIG_DIR / 'secret_key.txt'

    # Try to load from file (Docker/Production)
    if secret_key_file.exists():
        with open(secret_key_file, 'r') as f:
            return f.read().strip()

    # Try environment variable
    env_secret = os.getenv('DJANGO_SECRET_KEY')
    if env_secret:
        return env_secret

    # Fallback for local development only
    # WARNING: This should NEVER be used in production
    return 'django-insecure-LOCAL-DEV-ONLY-m#v&3r-oet$@=^o(vv47^s)z1s)l@#)_&)&!5o8r7x&z*q@7)e'

SECRET_KEY = load_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
# TODO: Set this to False in production and configure logging
DEBUG = True

ALLOWED_HOSTS = ['*'] # TODO: Restrict this to specific domains in production


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'webapp',
    # Third-party apps
    'crispy_forms',
    'crispy_bootstrap5',
    'csp', 

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',  
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'medinet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.getenv('TEMPLATES_DIR', os.path.join(BASE_DIR, 'templates'))],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'webapp.base_views.notifications_processor',

            ],
        },
    },
]

WSGI_APPLICATION = 'medinet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Original SQLite configuration
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.getenv('DB_PATH', BASE_DIR / 'db.sqlite3'),
    }
}

# PostgreSQL configuration
#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql',
#        'NAME': 'medinet_db',
#        'USER': 'medinet_user',
#        'PASSWORD': 'your_secure_password',  # FILL THIS IN WITH YOUR PASSWORD
#        'HOST': '127.0.0.1',
#        'PORT': '5432',
#        'OPTIONS': {
#            'client_encoding': 'UTF8'
#        },
#    }
#}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# ==============================================================================
# SECURITY: Fernet Encryption Keys Configuration
# ==============================================================================
# Encryption key for database field encryption.
# IMPORTANT: This key must remain fixed for encrypted data to remain valid.
#
# The FERNET_KEYS are loaded from a file for better security:
# 1. In Docker: Auto-generated on first run by entrypoint.sh
# 2. In local dev: Falls back to environment variable or default

def load_fernet_keys():
    """
    Load FERNET_KEYS from file, environment variable, or fallback to default.
    Priority: File > Environment Variable > Default (dev only)
    Returns: List of Fernet keys as bytes
    """
    fernet_keys_file = CONFIG_DIR / 'fernet_keys.txt'

    # Try to load from file (Docker/Production)
    if fernet_keys_file.exists():
        with open(fernet_keys_file, 'r') as f:
            keys_json = json.load(f)
            # Convert string keys to bytes
            return [key.encode('utf-8') for key in keys_json]

    # Try environment variable (expects JSON array)
    env_fernet = os.getenv('DJANGO_FERNET_KEYS')
    if env_fernet:
        keys_json = json.loads(env_fernet)
        return [key.encode('utf-8') for key in keys_json]

    # Fallback for local development only
    # WARNING: This should NEVER be used in production
    return [b'ZmDfcTF7_60GrrY167zsiPd67pEvs0aGOv2oasOM1Pg=']

FERNET_KEYS = load_fernet_keys()


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.getenv('STATIC_FILES_DIR', os.path.join(BASE_DIR, 'static')),
]
STATIC_ROOT = os.getenv('STATIC_ROOT', os.path.join(BASE_DIR, 'staticfiles'))

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.getenv('MEDIA_ROOT', os.path.join(BASE_DIR, 'media'))

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
LOGIN_REDIRECT_URL = 'user_dashboard'  # Redirect to dashboard after login
LOGOUT_REDIRECT_URL = 'home'  # Redirects here after logout
LOGIN_URL = 'login'

# Crispy Forms Settings
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Custom Rate Limiting Constants for webapp/decorators.py
RATE_LIMITS = {
    'REGISTER': '5/m',
    'CONNECTION_TEST': '20/m',
    'START_TRAINING': '20/m',
    'SAVE_MODEL_CONFIG': '30/m',
    'DELETE_MODEL_CONFIG': '30/m',
    'MANAGE_DATASETS': '60/m',
    'GENERAL_ACTIONS': '60/m', # Para profile, models_list, etc.
}

# Cache configuration for rate limiting
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'medinet_cache_table',
    }
}

# =============================================================================
# SECURITY SETTINGS - Content Security Policy (CSP)
# =============================================================================

# Security headers
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
X_FRAME_OPTIONS = 'DENY'

# Content Security Policy Configuration (django-csp 4.0+ format)
CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'base-uri': ("'self'",),
        'block-all-mixed-content': True,
        'connect-src': ("'self'", 'ws:', 'wss:'),
        'default-src': ("'self'",),
        'font-src': (
            "'self'",
            'fonts.gstatic.com',
            'fonts.googleapis.com',
            'cdn.jsdelivr.net',
            'cdnjs.cloudflare.com'
        ),
        'form-action': ("'self'",),
        'frame-ancestors': ("'none'",),
        'frame-src': ("'self'",),
        'img-src': (
            "'self'",
            'data:',  # For data URLs (base64 images)
            'blob:',  # For blob URLs
            '*.gravatar.com',
            'via.placeholder.com'
        ),
        'manifest-src': ("'self'",),
        'media-src': ("'self'",),
        'object-src': ("'none'",),
        'script-src': (
            "'self'",
            "'unsafe-inline'",  # Needed for inline scripts in templates
            "'unsafe-eval'",    # Needed for some JavaScript libraries
            'cdn.jsdelivr.net',
            'cdnjs.cloudflare.com',
            'code.jquery.com',
            'stackpath.bootstrapcdn.com',
            'unpkg.com'
        ),
        'style-src': (
            "'self'",
            "'unsafe-inline'",  # Needed for inline styles
            'fonts.googleapis.com',
            'cdn.jsdelivr.net',
            'cdnjs.cloudflare.com',
            'stackpath.bootstrapcdn.com',
            'unpkg.com'
        ),
        'upgrade-insecure-requests': True,
        'worker-src': ("'self'",)
    }
}

# Report violations (for monitoring)
# CSP_REPORT_ONLY = False  # Set to True for testing, False for enforcement

# Optional: CSP violation reporting endpoint
# CSP_REPORT_URI = '/csp-violation-report/'
