# Generated by Django 5.1.7 on 2025-04-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_trainingjob_clients_status_trainingjob_config_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingjob',
            name='training_duration',
            field=models.FloatField(blank=True, help_text='Total training duration in seconds', null=True),
        ),
    ]
