# Generated by Django 5.1.7 on 2025-05-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_trainingjob_training_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingjob',
            name='server_pid',
            field=models.IntegerField(blank=True, help_text='PID of the Flower server process', null=True),
        ),
        migrations.AlterField(
            model_name='trainingjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('server_ready', 'Server Ready'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
