# Generated by Django 5.2.3 on 2025-06-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_project_connection_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconfig',
            name='model_type',
            field=models.CharField(choices=[('dl', 'Deep Learning'), ('ml', 'Machine Learning')], default='dl', max_length=2),
        ),
    ]
