# Generated by Django 5.2.4 on 2025-07-07 07:59

import webapp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_modelconfig_model_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='password',
            field=webapp.models.EncryptedTextField(blank=True, null=True),
        ),
    ]
