# Generated by Django 5.2.4 on 2025-07-09 14:20

import django.db.models.deletion
import webapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_connection_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingjob',
            name='save_frequency',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Guardar un checkpoint cada X rondas. 0 para guardar solo al final.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='storage_used',
            field=models.BigIntegerField(default=0, help_text='Almacenamiento total usado en bytes.'),
        ),
        migrations.CreateModel(
            name='ModelArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(max_length=20)),
                ('round_number', models.PositiveIntegerField(blank=True, null=True)),
                ('file', models.FileField(upload_to=webapp.models.get_artifact_upload_path)),
                ('file_size', models.BigIntegerField(help_text='Tamaño del archivo en bytes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='webapp.trainingjob')),
            ],
        ),
    ]
