# Generated by Django 5.2.4 on 2025-07-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_trainingjob_save_frequency_userprofile_storage_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingjob',
            name='clients_config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuración de clientes para este job', null=True),
        ),
        migrations.AlterField(
            model_name='modelartifact',
            name='file_size',
            field=models.BigIntegerField(help_text='Size of the file in bytes.'),
        ),
        migrations.AlterField(
            model_name='trainingjob',
            name='save_frequency',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Save a checkpoint every X rounds. 0 to save only the final model.', null=True),
        ),
    ]
