# Generated by Django 5.2.3 on 2025-08-29 08:53

import webapp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_trainingjob_clients_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='api_key',
            field=webapp.models.EncryptedTextField(blank=True, null=True),
        ),
    ]
